// Auto-generated from templates/admin.html
// Do not edit this file directly

export const ADMIN_HTML = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Token 管理 - FlareMsg</title>
    <style>
        /* 暗黑主题（默认） */
        :root {
            --bg-primary: #0D1117;
            --bg-secondary: #161B22;
            --bg-tertiary: #21262D;
            --bg-input: #0D1117;
            --border-color: #30363D;
            --border-hover: #8B949E;
            --text-primary: #F0F6FC;
            --text-secondary: #8B949E;
            --text-muted: #6E7681;
            --primary: #07C160;
            --primary-hover: #06AD56;
            --danger: #DA3633;
            --danger-hover: #F85149;
            --success: #3FB950;
            --error: #F85149;
            --shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
        }

        /* 浅色主题 */
        .light-mode {
            --bg-primary: #FFFFFF;
            --bg-secondary: #F6F8FA;
            --bg-tertiary: #EAECEF;
            --bg-input: #FFFFFF;
            --border-color: #D0D7DE;
            --border-hover: #57606A;
            --text-primary: #24292F;
            --text-secondary: #57606A;
            --text-muted: #8B949E;
            --shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
        }

        /* 主题切换按钮 */
        .theme-toggle {
            position: fixed;
            top: 20px;
            right: 20px;
            width: 44px;
            height: 44px;
            border-radius: 50%;
            background: var(--bg-secondary);
            border: 1px solid var(--border-color);
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            transition: all 0.3s ease;
            z-index: 1000;
            box-shadow: var(--shadow);
        }

        .theme-toggle:hover {
            transform: scale(1.05);
        }

        .theme-toggle svg {
            width: 20px;
            height: 20px;
            transition: transform 0.3s ease;
        }

        .theme-toggle .sun-icon {
            display: none;
        }

        .theme-toggle .moon-icon {
            display: block;
        }

        .light-mode .theme-toggle .sun-icon {
            display: block;
        }

        .light-mode .theme-toggle .moon-icon {
            display: none;
        }

        @media (max-width: 768px) {
            .theme-toggle {
                top: 12px;
                right: 12px;
                width: 40px;
                height: 40px;
            }

            .theme-toggle svg {
                width: 18px;
                height: 18px;
            }
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--bg-primary);
            color: var(--text-primary);
            min-height: 100vh;
            padding: 20px;
            transition: background 0.3s ease, color 0.3s ease;
        }

        @media (max-width: 768px) {
            body {
                padding: 12px;
            }
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }

        .header {
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 1px solid var(--border-color);
            transition: border-color 0.3s ease;
        }

        .header h1 {
            font-size: 28px;
            margin-bottom: 10px;
            transition: color 0.3s ease;
        }

        .header a {
            color: var(--primary);
            text-decoration: none;
            transition: color 0.3s ease;
        }

        .header a:hover {
            text-decoration: underline;
        }

        .auth-section {
            background: var(--bg-secondary);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 24px;
            margin-bottom: 30px;
            transition: background 0.3s ease, border-color 0.3s ease;
        }

        @media (max-width: 768px) {
            .auth-section {
                padding: 20px;
                border-radius: 10px;
            }
        }

        .auth-section h2 {
            font-size: 18px;
            margin-bottom: 16px;
            color: var(--text-primary);
        }

        .input-group {
            margin-bottom: 16px;
        }

        .input-group label {
            display: block;
            margin-bottom: 8px;
            color: var(--text-secondary);
            font-size: 14px;
            font-weight: 500;
        }

        input[type="text"],
        input[type="password"] {
            width: 100%;
            padding: 12px 16px;
            background: var(--bg-input);
            border: 1px solid var(--border-color);
            border-radius: 8px;
            color: var(--text-primary);
            font-size: 15px;
            transition: all 0.2s ease;
        }

        input:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 3px rgba(7, 193, 96, 0.1);
        }

        @media (max-width: 768px) {
            input[type="text"],
            input[type="password"] {
                font-size: 16px; /* 防止 iOS 自动缩放 */
            }
        }

        button {
            padding: 12px 24px;
            background: var(--primary);
            color: white;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            font-size: 15px;
            font-weight: 500;
            transition: all 0.2s ease;
        }

        button:hover {
            background: var(--primary-hover);
            transform: translateY(-1px);
            box-shadow: var(--shadow);
        }

        button:active {
            transform: translateY(0);
        }

        button:disabled {
            background: var(--border-color);
            cursor: not-allowed;
            transform: none;
        }

        @media (hover: none) {
            button:hover {
                transform: none;
            }

            button:active {
                transform: scale(0.98);
            }
        }

        button.danger {
            background: var(--danger);
        }

        button.danger:hover {
            background: var(--danger-hover);
        }

        .content {
            display: none;
        }

        .content.visible {
            display: block;
        }

        .add-token-section {
            background: var(--bg-secondary);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 24px;
            margin-bottom: 30px;
            transition: background 0.3s ease, border-color 0.3s ease;
        }

        @media (max-width: 768px) {
            .add-token-section {
                padding: 20px;
            }
        }

        .add-token-section h2 {
            font-size: 18px;
            margin-bottom: 12px;
            color: var(--text-primary);
        }

        .add-token-section p {
            color: var(--text-secondary);
            margin-bottom: 16px;
            font-size: 14px;
            line-height: 1.5;
        }

        .token-list {
            background: var(--bg-secondary);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            padding: 24px;
            transition: background 0.3s ease, border-color 0.3s ease;
        }

        @media (max-width: 768px) {
            .token-list {
                padding: 20px;
            }
        }

        .token-list h2 {
            font-size: 18px;
            margin-bottom: 16px;
            color: var(--text-primary);
        }

        .token-item {
            display: flex;
            align-items: center;
            padding: 16px;
            background: var(--bg-tertiary);
            border: 1px solid var(--border-color);
            border-radius: 8px;
            margin-bottom: 12px;
            transition: background 0.3s ease, border-color 0.3s ease;
        }

        @media (max-width: 768px) {
            .token-item {
                flex-direction: column;
                align-items: flex-start;
                gap: 12px;
                padding: 12px;
            }

            .token-info {
                margin-right: 0 !important;
                width: 100% !important;
            }

            .token-actions {
                width: 100%;
                flex-direction: column;
                gap: 8px;
            }

            .token-actions button {
                width: 100%;
            }
        }

        .token-info {
            flex: 1;
            margin-right: 20px;
            min-width: 0;
        }

        .token-key {
            font-family: 'Monaco', 'Courier New', monospace;
            font-size: 15px;
            margin-bottom: 6px;
            color: var(--primary);
            word-break: break-all;
        }

        .token-value {
            font-size: 13px;
            color: var(--text-secondary);
            word-break: break-all;
        }

        .token-actions {
            display: flex;
            gap: 8px;
            flex-shrink: 0;
        }

        @media (max-width: 480px) {
            .token-actions {
                flex-direction: column;
                width: 100%;
            }

            .token-actions button {
                width: 100%;
            }
        }

        .alert {
            padding: 14px 18px;
            border-radius: 8px;
            margin-bottom: 20px;
            display: none;
            animation: slideIn 0.3s ease;
        }

        @keyframes slideIn {
            from {
                opacity: 0;
                transform: translateY(-10px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .alert.show {
            display: block;
        }

        .alert.success {
            background: rgba(63, 185, 80, 0.1);
            border: 1px solid rgba(63, 185, 80, 0.3);
            color: var(--success);
        }

        .alert.error {
            background: rgba(218, 54, 51, 0.1);
            border: 1px solid rgba(218, 54, 51, 0.3);
            color: var(--error);
        }

        .empty-state {
            text-align: center;
            padding: 48px 24px;
            color: var(--text-secondary);
        }

        @media (max-width: 768px) {
            .empty-state {
                padding: 32px 16px;
            }
        }

        /* 触摸优化 */
        @media (hover: none) and (pointer: coarse) {
            button {
                min-height: 44px; /* 推荐的触摸目标最小尺寸 */
                font-size: 16px;
            }

            button:active {
                transform: scale(0.98);
            }
        }
    </style>
</head>
<body>
    <!-- Theme Toggle Button -->
    <button class="theme-toggle" onclick="toggleTheme()" aria-label="切换主题">
        <svg class="moon-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="4"/>
            <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/>
        </svg>
        <svg class="sun-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="5"/>
            <line x1="12" y1="1" x2="12" y2="3"/>
            <line x1="12" y1="21" x2="12" y2="23"/>
            <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/>
            <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/>
            <line x1="1" y1="12" x2="3" y2="12"/>
            <line x1="21" y1="12" x2="23" y2="12"/>
            <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/>
            <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>
        </svg>
    </button>

    <div class="container">
        <div class="header">
            <h1>🔑 Token 管理</h1>
            <a href="/">← 返回首页</a>
        </div>

        <div id="authSection" class="auth-section">
            <h2>身份验证</h2>
            <div class="input-group">
                <label for="adminToken">管理员 Token (CLIENT_AUTH_TOKEN)</label>
                <input type="password" id="adminToken" placeholder="请输入管理员 Token">
            </div>
            <button onclick="login()">登录</button>
        </div>

        <div id="content" class="content">
            <div id="alert" class="alert"></div>

            <div class="add-token-section">
                <h2>添加用户 Token</h2>
                <p style="color: #8b949e; margin-bottom: 15px;">输入用户的 OpenID，系统将自动生成 sk_ 开头的 Token</p>
                <div class="input-group">
                    <label for="openid">用户 OpenID</label>
                    <input type="text" id="openid" placeholder="例如：oxxxxxxxxxxxxxxxxxxxxxxx">
                </div>
                <button onclick="addToken()">添加 Token</button>
            </div>

            <div class="token-list">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 15px;">
                    <h2 style="margin: 0;">用户 Token 列表</h2>
                    <button onclick="loadTokens()" style="padding: 8px 16px; font-size: 14px; background: var(--bg-tertiary); border: 1px solid var(--border-color); border-radius: 6px; cursor: pointer; color: var(--text-primary);">🔄 刷新</button>
                </div>
                <div id="tokenStats" style="color: var(--text-secondary); font-size: 13px; margin-bottom: 10px;"></div>
                <div id="tokenList"></div>
            </div>
        </div>
    </div>

    <script>
        // 主题切换功能
        function initTheme() {
            const savedTheme = localStorage.getItem('theme');
            if (savedTheme === 'light') {
                document.body.classList.add('light-mode');
            }
        }

        function toggleTheme() {
            const isLight = document.body.classList.toggle('light-mode');
            localStorage.setItem('theme', isLight ? 'light' : 'dark');
        }

        // 页面加载时初始化主题
        initTheme();

        let authToken = '';

        function showAlert(message, type) {
            const alert = document.getElementById('alert');
            alert.textContent = message;
            alert.className = 'alert ' + type + ' show';
            setTimeout(() => alert.classList.remove('show'), 5000);
        }

        async function login() {
            const token = document.getElementById('adminToken').value.trim();
            if (!token) {
                showAlert('请输入管理员 Token', 'error');
                return;
            }

            try {
                const response = await fetch('/admin/api/tokens', {
                    headers: {
                        'Authorization': 'Bearer ' + token
                    }
                });

                if (response.ok) {
                    authToken = token;
                    document.getElementById('authSection').style.display = 'none';
                    document.getElementById('content').classList.add('visible');
                    loadTokens();
                } else {
                    const data = await response.json();
                    showAlert(data.error || '认证失败', 'error');
                }
            } catch (error) {
                showAlert('网络错误: ' + error.message, 'error');
            }
        }

        async function loadTokens() {
            const container = document.getElementById('tokenList');
            const stats = document.getElementById('tokenStats');

            // 显示加载状态
            container.innerHTML = '<div class="empty-state">⏳ 正在加载...</div>';
            stats.textContent = '';

            try {
                console.log('[DEBUG] Fetching tokens from /admin/api/tokens');
                const response = await fetch('/admin/api/tokens', {
                    headers: {
                        'Authorization': 'Bearer ' + authToken
                    }
                });

                console.log('[DEBUG] Response status:', response.status);
                console.log('[DEBUG] Response ok:', response.ok);

                if (response.ok) {
                    const data = await response.json();
                    console.log('[DEBUG] Response data:', data);
                    displayTokens(data.tokens);
                    stats.textContent = '共找到 ' + data.tokens.length + ' 个 Token';
                } else {
                    const errorData = await response.json().catch(() => ({ error: 'Unknown error' }));
                    console.error('[ERROR] Failed to load tokens:', errorData);
                    showAlert('加载 Token 列表失败: ' + (errorData.error || '未知错误'), 'error');
                    container.innerHTML = '<div class="empty-state">❌ 加载失败</div>';
                }
            } catch (error) {
                console.error('[ERROR] Network error:', error);
                showAlert('网络错误: ' + error.message, 'error');
                container.innerHTML = '<div class="empty-state">❌ 网络错误</div>';
            }
        }

        function displayTokens(tokens) {
            const container = document.getElementById('tokenList');

            if (tokens.length === 0) {
                container.innerHTML = '<div class="empty-state">暂无用户 Token</div>';
                return;
            }

            container.innerHTML = tokens.map(token => '<div class="token-item"><div class="token-info"><div class="token-key">' + token.key + '</div><div class="token-value">' + token.value + '</div></div><div class="token-actions"><button class="danger" onclick="deleteToken(\\'' + token.key + '\\')">删除</button><button onclick="copyToClipboard(\\'' + token.key + '\\')">复制 Token</button></div></div>').join('');
        }

        async function addToken() {
            const openid = document.getElementById('openid').value.trim();
            if (!openid) {
                showAlert('请输入用户 OpenID', 'error');
                return;
            }

            try {
                const response = await fetch('/admin/api/tokens', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        'Authorization': 'Bearer ' + authToken
                    },
                    body: JSON.stringify({ openid })
                });

                if (response.ok) {
                    const data = await response.json();
                    showAlert('Token 添加成功: ' + data.key, 'success');
                    document.getElementById('openid').value = '';
                    loadTokens();
                } else {
                    const data = await response.json();
                    showAlert(data.error || '添加失败', 'error');
                }
            } catch (error) {
                showAlert('网络错误: ' + error.message, 'error');
            }
        }

        async function deleteToken(key) {
            if (!confirm('确定要删除这个 Token 吗？')) return;

            try {
                const response = await fetch('/admin/api/tokens?' + new URLSearchParams({ key }), {
                    method: 'DELETE',
                    headers: {
                        'Authorization': 'Bearer ' + authToken
                    }
                });

                if (response.ok) {
                    showAlert('Token 删除成功', 'success');
                    loadTokens();
                } else {
                    const data = await response.json();
                    showAlert(data.error || '删除失败', 'error');
                }
            } catch (error) {
                showAlert('网络错误: ' + error.message, 'error');
            }
        }

        function copyToClipboard(text) {
            navigator.clipboard.writeText(text).then(() => {
                showAlert('Token 已复制到剪贴板', 'success');
            }).catch(() => {
                showAlert('复制失败', 'error');
            });
        }

        // 支持回车登录
        document.getElementById('adminToken').addEventListener('keypress', (e) => {
            if (e.key === 'Enter') login();
        });

        // 支持回车添加 Token
        document.getElementById('openid').addEventListener('keypress', (e) => {
            if (e.key === 'Enter') addToken();
        });
    </script>
</body>
</html>

`;
