// Auto-generated from templates/index.html
// Do not edit this file directly

export const INDEX_HTML = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FlareMsg - 微信消息推送</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
    <style>
        /* 暗黑主题（默认） */
        :root {
            --wechat-green: #07C160;
            --wechat-green-dark: #06AD56;
            --wechat-green-light: #1DB954;
            --bg-primary: #0D1117;
            --bg-secondary: #161B22;
            --bg-tertiary: #21262D;
            --bg-input: #0D1117;
            --border-color: #30363D;
            --border-hover: #8B949E;
            --text-primary: #F0F6FC;
            --text-secondary: #8B949E;
            --text-muted: #6E7681;
            --error: #F85149;
            --success: #3FB950;
            --warning: #D29922;
            --glow-green: rgba(7, 193, 96, 0.4);
            --glow-blue: rgba(88, 166, 255, 0.3);
            --shadow-card: 0 32px 64px rgba(0, 0, 0, 0.4);
            --shadow-button: 0 12px 40px var(--glow-green);
        }

        /* 浅色主题 */
        .light-mode {
            --bg-primary: #FFFFFF;
            --bg-secondary: #F6F8FA;
            --bg-tertiary: #EAECEF;
            --bg-input: #FFFFFF;
            --border-color: #D0D7DE;
            --border-hover: #57606A;
            --text-primary: #24292F;
            --text-secondary: #57606A;
            --text-muted: #8B949E;
            --shadow-card: 0 2px 16px rgba(0, 0, 0, 0.08);
            --shadow-button: 0 4px 24px rgba(7, 193, 96, 0.3);
        }

        /* 主题切换按钮 */
        .theme-toggle {
            position: fixed;
            top: 20px;
            right: 20px;
            width: 44px;
            height: 44px;
            border-radius: 50%;
            background: var(--bg-secondary);
            border: 1px solid var(--border-color);
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            transition: all 0.3s ease;
            z-index: 1000;
            box-shadow: var(--shadow);
        }

        .theme-toggle:hover {
            transform: scale(1.05);
            box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);
        }

        .theme-toggle svg {
            width: 20px;
            height: 20px;
            transition: transform 0.3s ease;
        }

        .theme-toggle .sun-icon {
            display: none;
        }

        .theme-toggle .moon-icon {
            display: block;
        }

        .light-mode .theme-toggle .sun-icon {
            display: block;
        }

        .light-mode .theme-toggle .moon-icon {
            display: none;
        }

        @media (max-width: 768px) {
            .theme-toggle {
                top: 12px;
                right: 12px;
                width: 40px;
                height: 40px;
            }

            .theme-toggle svg {
                width: 18px;
                height: 18px;
            }
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Outfit', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--bg-primary);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 16px;
            position: relative;
            overflow-x: hidden;
            transition: background 0.3s ease, color 0.3s ease;
        }

        /* Animated background particles */
        .particles {
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            pointer-events: none;
            overflow: hidden;
            z-index: 0;
        }

        .particle {
            position: absolute;
            width: 4px;
            height: 4px;
            background: var(--wechat-green);
            border-radius: 50%;
            opacity: 0.3;
            animation: float 15s infinite ease-in-out;
        }

        .particle:nth-child(1) { left: 10%; animation-delay: 0s; }
        .particle:nth-child(2) { left: 20%; animation-delay: 1s; }
        .particle:nth-child(3) { left: 30%; animation-delay: 2s; }
        .particle:nth-child(4) { left: 40%; animation-delay: 3s; }
        .particle:nth-child(5) { left: 50%; animation-delay: 4s; }
        .particle:nth-child(6) { left: 60%; animation-delay: 5s; }
        .particle:nth-child(7) { left: 70%; animation-delay: 6s; }
        .particle:nth-child(8) { left: 80%; animation-delay: 7s; }
        .particle:nth-child(9) { left: 90%; animation-delay: 8s; }

        @keyframes float {
            0%, 100% {
                transform: translateY(100vh) scale(0);
                opacity: 0;
            }
            10% {
                opacity: 0.3;
                transform: translateY(80vh) scale(1);
            }
            90% {
                opacity: 0.3;
                transform: translateY(10vh) scale(1);
            }
            100% {
                transform: translateY(0) scale(0);
                opacity: 0;
            }
        }

        /* Gradient orbs */
        .orb {
            position: fixed;
            border-radius: 50%;
            filter: blur(120px);
            opacity: 0.15;
            z-index: 0;
            animation: orb-pulse 8s infinite ease-in-out;
        }

        .orb-1 {
            width: 400px;
            height: 400px;
            background: var(--wechat-green);
            top: -100px;
            left: -100px;
        }

        .orb-2 {
            width: 300px;
            height: 300px;
            background: #58A6FF;
            bottom: -50px;
            right: -50px;
            animation-delay: -4s;
        }

        @keyframes orb-pulse {
            0%, 100% { transform: scale(1); opacity: 0.15; }
            50% { transform: scale(1.2); opacity: 0.2; }
        }

        /* Main container */
        .container {
            position: relative;
            z-index: 1;
            width: 100%;
            max-width: 520px;
        }

        /* Card with glass effect */
        .card {
            background: var(--bg-secondary);
            backdrop-filter: blur(20px);
            -webkit-backdrop-filter: blur(20px);
            border: 1px solid var(--border-color);
            border-radius: 24px;
            padding: 48px 40px;
            box-shadow: var(--shadow-card);
            transition: background 0.3s ease, border-color 0.3s ease, box-shadow 0.3s ease;
        }

        @media (max-width: 768px) {
            .card {
                padding: 32px 24px;
                border-radius: 20px;
            }
        }

        @media (max-width: 480px) {
            .card {
                padding: 24px 16px;
                border-radius: 16px;
            }
        }

        /* Header */
        .header {
            text-align: center;
            margin-bottom: 40px;
        }

        .logo {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 72px;
            height: 72px;
            background: linear-gradient(135deg, var(--wechat-green) 0%, var(--wechat-green-dark) 100%);
            border-radius: 20px;
            margin-bottom: 20px;
            box-shadow:
                0 8px 32px var(--glow-green),
                0 0 0 1px rgba(255, 255, 255, 0.1) inset;
            animation: logo-glow 3s infinite ease-in-out;
        }

        .logo svg {
            width: 40px;
            height: 40px;
            fill: white;
        }

        @keyframes logo-glow {
            0%, 100% { box-shadow: 0 8px 32px var(--glow-green), 0 0 0 1px rgba(255, 255, 255, 0.1) inset; }
            50% { box-shadow: 0 8px 48px var(--glow-green), 0 0 0 1px rgba(255, 255, 255, 0.1) inset; }
        }

        .header h1 {
            font-family: 'Outfit', sans-serif;
            font-size: 28px;
            font-weight: 700;
            color: var(--text-primary);
            margin-bottom: 8px;
            letter-spacing: -0.5px;
        }

        .header p {
            font-family: 'Outfit', sans-serif;
            font-size: 15px;
            color: var(--text-secondary);
            font-weight: 400;
        }

        /* Status indicator */
        .status-badge {
            display: inline-flex;
            align-items: center;
            gap: 6px;
            padding: 6px 12px;
            background: rgba(7, 193, 96, 0.1);
            border: 1px solid rgba(7, 193, 96, 0.3);
            border-radius: 20px;
            margin-top: 16px;
            font-size: 12px;
            color: var(--wechat-green);
            font-weight: 500;
        }

        .status-badge::before {
            content: '';
            width: 6px;
            height: 6px;
            background: var(--wechat-green);
            border-radius: 50%;
            animation: pulse-dot 2s infinite;
        }

        @keyframes pulse-dot {
            0%, 100% { opacity: 1; transform: scale(1); }
            50% { opacity: 0.5; transform: scale(1.2); }
        }

        /* Form */
        .form {
            display: flex;
            flex-direction: column;
            gap: 24px;
        }

        .form-group {
            position: relative;
        }

        .form-group label {
            display: flex;
            align-items: center;
            gap: 6px;
            font-family: 'Outfit', sans-serif;
            font-size: 13px;
            font-weight: 500;
            color: var(--text-secondary);
            margin-bottom: 10px;
            letter-spacing: 0.3px;
        }

        .form-group label .required {
            color: var(--error);
            font-weight: 600;
        }

        .input-wrapper {
            position: relative;
        }

        .form-group input,
        .form-group textarea {
            width: 100%;
            padding: 16px 18px;
            background: var(--bg-input);
            border: 1px solid var(--border-color);
            border-radius: 12px;
            font-family: 'Outfit', sans-serif;
            font-size: 15px;
            color: var(--text-primary);
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            letter-spacing: 0.2px;
        }

        .form-group input::placeholder,
        .form-group textarea::placeholder {
            color: var(--text-muted);
        }

        .form-group input:hover,
        .form-group textarea:hover {
            border-color: rgba(7, 193, 96, 0.4);
        }

        .form-group input:focus,
        .form-group textarea:focus {
            outline: none;
            border-color: var(--wechat-green);
            box-shadow: 0 0 0 4px var(--glow-green);
        }

        .form-group textarea {
            resize: vertical;
            min-height: 120px;
            line-height: 1.6;
        }

        .form-group small {
            display: block;
            margin-top: 8px;
            font-size: 12px;
            color: var(--text-muted);
            font-family: 'Outfit', sans-serif;
        }

        /* Icon inside input */
        .input-icon {
            position: absolute;
            right: 16px;
            top: 50%;
            transform: translateY(-50%);
            color: var(--text-muted);
            pointer-events: none;
            transition: color 0.3s;
        }

        .form-group input:focus + .input-icon,
        .input-wrapper:focus-within .input-icon {
            color: var(--wechat-green);
        }

        /* Submit button */
        .btn-submit {
            position: relative;
            width: 100%;
            padding: 18px 24px;
            background: linear-gradient(135deg, var(--wechat-green) 0%, var(--wechat-green-dark) 100%);
            color: white;
            border: none;
            border-radius: 14px;
            font-family: 'Outfit', sans-serif;
            font-size: 16px;
            font-weight: 600;
            cursor: pointer;
            overflow: hidden;
            transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
            margin-top: 8px;
            letter-spacing: 0.5px;
        }

        .btn-submit::before {
            content: '';
            position: absolute;
            top: 0;
            left: -100%;
            width: 100%;
            height: 100%;
            background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.2), transparent);
            transition: left 0.5s;
        }

        .btn-submit:hover::before {
            left: 100%;
        }

        .btn-submit:hover {
            transform: translateY(-2px);
            box-shadow: 0 12px 40px var(--glow-green);
        }

        .btn-submit:active {
            transform: translateY(0);
        }

        .btn-submit:disabled {
            background: var(--border-color);
            cursor: not-allowed;
            transform: none;
            box-shadow: none;
        }

        .btn-submit:disabled::before {
            display: none;
        }

        .btn-submit .spinner {
            display: none;
            width: 20px;
            height: 20px;
            border: 2px solid rgba(255, 255, 255, 0.3);
            border-top-color: white;
            border-radius: 50%;
            animation: spin 0.8s linear infinite;
            margin-right: 8px;
        }

        .btn-submit.loading .spinner {
            display: inline-block;
        }

        .btn-submit.loading .btn-text {
            opacity: 0.8;
        }

        @keyframes spin {
            to { transform: rotate(360deg); }
        }

        /* Alert */
        .alert {
            padding: 16px 20px;
            border-radius: 12px;
            display: none;
            align-items: flex-start;
            gap: 12px;
            animation: alert-slide 0.3s ease-out;
        }

        @keyframes alert-slide {
            from {
                opacity: 0;
                transform: translateY(-10px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        .alert.show {
            display: flex;
        }

        .alert.success {
            background: rgba(63, 185, 80, 0.1);
            border: 1px solid rgba(63, 185, 80, 0.3);
            color: var(--success);
        }

        .alert.error {
            background: rgba(248, 81, 73, 0.1);
            border: 1px solid rgba(248, 81, 73, 0.3);
            color: var(--error);
        }

        .alert-icon {
            flex-shrink: 0;
            width: 20px;
            height: 20px;
        }

        .alert.success .alert-icon {
            fill: var(--success);
        }

        .alert.error .alert-icon {
            fill: var(--error);
        }

        .alert-content {
            flex: 1;
        }

        .alert-title {
            font-weight: 600;
            margin-bottom: 4px;
            font-family: 'Outfit', sans-serif;
        }

        .alert-message {
            font-size: 14px;
            opacity: 0.9;
            font-family: 'Outfit', sans-serif;
        }

        /* Footer */
        .footer {
            text-align: center;
            margin-top: 40px;
            padding-top: 24px;
            border-top: 1px solid var(--border-color);
        }

        .footer-links {
            display: flex;
            justify-content: center;
            gap: 24px;
        }

        .footer-links a {
            display: inline-flex;
            align-items: center;
            gap: 6px;
            color: var(--text-muted);
            text-decoration: none;
            font-size: 13px;
            font-family: 'Outfit', sans-serif;
            transition: color 0.3s;
        }

        .footer-links a:hover {
            color: var(--wechat-green);
        }

        .footer-links a svg {
            width: 16px;
            height: 16px;
            fill: currentColor;
        }

        .copyright {
            margin-top: 16px;
            font-size: 12px;
            color: var(--text-muted);
            font-family: 'Outfit', sans-serif;
        }

        /* Quick preset buttons */
        .preset-bar {
            display: flex;
            gap: 8px;
            margin-bottom: 20px;
            flex-wrap: wrap;
        }

        .preset-btn {
            padding: 6px 12px;
            background: rgba(7, 193, 96, 0.1);
            border: 1px solid rgba(7, 193, 96, 0.2);
            border-radius: 8px;
            color: var(--wechat-green);
            font-size: 12px;
            font-family: 'Outfit', sans-serif;
            cursor: pointer;
            transition: all 0.3s;
        }

        .preset-btn:hover {
            background: rgba(7, 193, 96, 0.2);
            border-color: rgba(7, 193, 96, 0.4);
        }

        /* Responsive Design */
        @media (max-width: 768px) {
            body {
                padding: 12px;
            }

            .card {
                padding: 32px 24px;
                border-radius: 20px;
            }

            .header h1 {
                font-size: 24px;
            }

            .logo {
                width: 60px;
                height: 60px;
            }

            .logo svg {
                width: 32px;
                height: 32px;
            }

            .preset-bar {
                flex-direction: column;
                gap: 8px;
            }

            .preset-btn {
                width: 100%;
                text-align: center;
            }
        }

        @media (max-width: 480px) {
            body {
                padding: 8px;
            }

            .card {
                padding: 24px 16px;
                border-radius: 16px;
            }

            .header h1 {
                font-size: 22px;
            }

            .header p {
                font-size: 14px;
            }

            .btn-submit {
                padding: 16px 20px;
                font-size: 15px;
            }

            .form-group input,
            .form-group textarea {
                padding: 14px 16px;
                font-size: 14px;
            }

            .footer-links {
                flex-direction: column;
                gap: 12px;
            }

            .footer-links a {
                justify-content: center;
            }
        }

        /* 触摸优化 */
        @media (hover: none) and (pointer: coarse) {
            .btn-submit:hover {
                transform: none;
            }

            .btn-submit:active {
                transform: scale(0.98);
            }

            .preset-btn:hover {
                background: rgba(7, 193, 96, 0.1);
                border-color: rgba(7, 193, 96, 0.2);
            }

            .preset-btn:active {
                background: rgba(7, 193, 96, 0.2);
                transform: scale(0.98);
            }
        }
    </style>
</head>
<body>
    <!-- Theme Toggle Button -->
    <button class="theme-toggle" onclick="toggleTheme()" aria-label="切换主题">
        <svg class="moon-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="4"/>
            <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"/>
        </svg>
        <svg class="sun-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
            <circle cx="12" cy="12" r="5"/>
            <line x1="12" y1="1" x2="12" y2="3"/>
            <line x1="12" y1="21" x2="12" y2="23"/>
            <line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/>
            <line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/>
            <line x1="1" y1="12" x2="3" y2="12"/>
            <line x1="21" y1="12" x2="23" y2="12"/>
            <line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/>
            <line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/>
        </svg>
    </button>

    <!-- Animated background -->
    <div class="particles">
        <div class="particle"></div>
        <div class="particle"></div>
        <div class="particle"></div>
        <div class="particle"></div>
        <div class="particle"></div>
        <div class="particle"></div>
        <div class="particle"></div>
        <div class="particle"></div>
        <div class="particle"></div>
    </div>

    <div class="orb orb-1"></div>
    <div class="orb orb-2"></div>

    <div class="container">
        <div class="card">
            <div class="header">
                <div class="logo">
                    <svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8.691 2.188C3.891 2.188 0 5.476 0 9.53c0 2.212 1.17 4.203 3.002 5.55a.59.59 0 0 1 .213.665l-.39 1.48c-.019.07-.048.141-.048.213 0 .163.13.295.29.295a.326.326 0 0 0 .167-.054l1.903-1.114a.864.864 0 0 1 .717-.098 10.16 10.16 0 0 0 2.837.403c.276 0 .543-.027.811-.05-.857-2.578.157-4.972 1.932-6.446 1.703-1.415 3.882-1.98 5.853-1.838-.576-3.583-4.196-6.348-8.596-6.348zM5.785 5.991c.642 0 1.162.529 1.162 1.18a1.17 1.17 0 0 1-1.162 1.178A1.17 1.17 0 0 1 4.623 7.17c0-.651.52-1.18 1.162-1.18zm5.813 0c.642 0 1.162.529 1.162 1.18a1.17 1.17 0 0 1-1.162 1.178 1.17 1.17 0 0 1-1.162-1.178c0-.651.52-1.18 1.162-1.18zm5.34 2.867c-1.797-.052-3.746.512-5.28 1.786-1.72 1.428-2.687 3.72-1.78 6.22.942 2.453 3.666 4.229 6.884 4.229.826 0 1.622-.12 2.361-.336a.722.722 0 0 1 .598.082l1.584.926a.272.272 0 0 0 .14.047c.134 0 .24-.111.24-.247 0-.06-.023-.12-.038-.177l-.326-1.233a.492.492 0 0 1-.023-.156.49.49 0 0 1 .201-.398C23.024 18.48 24 16.82 24 14.98c0-3.21-2.931-5.837-7.062-6.122zm-3.798 3.387a.68.68 0 0 0-.68-.68.68.68 0 0 0-.68.68.68.68 0 0 0 .68.68.68.68 0 0 0 .68-.68zm4.742 0a.68.68 0 0 0-.68-.68.68.68 0 0 0-.68.68.68.68 0 0 0 .68.68.68.68 0 0 0 .68-.68z"/>
                    </svg>
                </div>
                <h1>FlareMsg</h1>
                <p>微信消息推送服务</p>
                <div class="status-badge">就绪</div>
                <div style="margin-top: 16px; font-size: 13px; color: #8b949e;">
                    <strong>API 端点:</strong> GET/POST <code style="background: #30363d; padding: 2px 6px; border-radius: 4px; font-family: 'JetBrains Mono', monospace;">/send</code>
                    <span style="margin: 0 8px;">|</span>
                    <a href="/admin" style="color: #58a6ff; text-decoration: none;">管理页面 →</a>
                </div>
            </div>

            <div id="alert" class="alert">
                <svg class="alert-icon" viewBox="0 0 24 24">
                    <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z"/>
                </svg>
                <div class="alert-content">
                    <div class="alert-title"></div>
                    <div class="alert-message"></div>
                </div>
            </div>

            <form id="messageForm">
                <div class="preset-bar">
                    <button type="button" class="preset-btn" data-preset="system">系统通知</button>
                    <button type="button" class="preset-btn" data-preset="alert">告警消息</button>
                    <button type="button" class="preset-btn" data-preset="info">信息推送</button>
                </div>

                <div class="form-group">
                    <label for="token">鉴权密钥 <span class="required">*</span></label>
                    <div class="input-wrapper">
                        <input type="password" id="token" name="token" required placeholder="请输入 CLIENT_AUTH_TOKEN">
                        <svg class="input-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <rect x="3" y="11" width="18" height="11" rx="2" ry="2"/>
                            <path d="M7 11V7a5 5 0 0 1 10 0v4"/>
                        </svg>
                    </div>
                </div>

                <div class="form-group">
                    <label for="openid">微信 OpenID <span class="required">*</span></label>
                    <div class="input-wrapper">
                        <input type="text" id="openid" name="openid" required placeholder="请输入接收者的微信 OpenID">
                        <svg class="input-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/>
                            <circle cx="12" cy="7" r="4"/>
                        </svg>
                    </div>
                    <small>消息接收者的微信 OpenID，可在测试号页面获取</small>
                </div>

                <div class="form-group">
                    <label for="from">消息来源</label>
                    <div class="input-wrapper">
                        <input type="text" id="from" name="from" placeholder="例如：系统监控">
                        <svg class="input-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/>
                            <polyline points="9,22 9,12 15,12 15,22"/>
                        </svg>
                    </div>
                </div>

                <div class="form-group">
                    <label for="desc">消息内容 <span class="required">*</span></label>
                    <textarea id="desc" name="desc" required placeholder="请输入要发送的消息内容..."></textarea>
                    <small>消息的主要内容，将显示在模版消息的正文部分</small>
                </div>

                <div class="form-group">
                    <label for="remark">备注信息</label>
                    <div class="input-wrapper">
                        <input type="text" id="remark" name="remark" placeholder="例如：请及时查看处理">
                        <svg class="input-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/>
                            <polyline points="14,2 14,8 20,8"/>
                            <line x1="16" y1="13" x2="8" y2="13"/>
                            <line x1="16" y1="17" x2="8" y2="17"/>
                        </svg>
                    </div>
                </div>

                <div class="form-group">
                    <label for="url">跳转链接</label>
                    <div class="input-wrapper">
                        <input type="url" id="url" name="url" placeholder="https://example.com">
                        <svg class="input-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/>
                            <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>
                        </svg>
                    </div>
                    <small>点击消息卡片后跳转的链接，可留空</small>
                </div>

                <button type="submit" class="btn-submit" id="submitBtn">
                    <span class="spinner"></span>
                    <span class="btn-text">发送消息</span>
                </button>
            </form>

            <div class="footer">
                <div class="footer-links">
                    <a href="https://github.com/sarices/FlareMsg" target="_blank">
                        <svg viewBox="0 0 24 24">
                            <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12z"/>
                        </svg>
                        GitHub
                    </a>
                    <a href="/admin" target="_blank">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2zm0 18a8 8 0 1 1 8-8 8 8 0 0 1-8 8z"/>
                            <path d="M12 6v6l4 2"/>
                        </svg>
                        管理页面
                    </a>
                    <a href="https://github.com/sarices/FlareMsg/issues" target="_blank">
                        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <circle cx="12" cy="12" r="10"/>
                            <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/>
                            <line x1="12" y1="17" x2="12.01" y2="17"/>
                        </svg>
                        反馈问题
                    </a>
                </div>
                <p class="copyright">Powered by Cloudflare Workers</p>
            </div>
        </div>
    </div>

    <script>
        const form = document.getElementById('messageForm');
        const submitBtn = document.getElementById('submitBtn');
        const alertEl = document.getElementById('alert');

        // Preset configurations
        const presets = {
            system: { from: '系统通知', remark: '来自系统自动推送' },
            alert: { from: '⚠️ 告警通知', remark: '请立即处理！' },
            info: { from: '信息推送', remark: '' }
        };

        // 主题切换功能
        function initTheme() {
            const savedTheme = localStorage.getItem('theme');
            if (savedTheme === 'light') {
                document.body.classList.add('light-mode');
            }
        }

        function toggleTheme() {
            const isLight = document.body.classList.toggle('light-mode');
            localStorage.setItem('theme', isLight ? 'light' : 'dark');
        }

        // 页面加载时初始化主题
        initTheme();

        // Load saved credentials
        window.addEventListener('DOMContentLoaded', () => {
            const savedToken = localStorage.getItem('flaremsg_token');
            const savedOpenid = localStorage.getItem('flaremsg_openid');
            if (savedToken) document.getElementById('token').value = savedToken;
            if (savedOpenid) document.getElementById('openid').value = savedOpenid;

            document.querySelectorAll('.preset-btn').forEach(btn => {
                btn.addEventListener('click', () => {
                    const preset = presets[btn.dataset.preset];
                    if (preset.from) document.getElementById('from').value = preset.from;
                    if (preset.remark) document.getElementById('remark').value = preset.remark;
                });
            });
        });

        // Show alert
        function showAlert(title, message, type) {
            const iconPath = type === 'success'
                ? 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-2 15l-5-5 1.41-1.41L10 14.17l7.59-7.59L19 8l-9 9z'
                : 'M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z';
            alertEl.innerHTML = '<svg class="alert-icon" viewBox="0 0 24 24"><path d="' + iconPath + '"/></svg><div class="alert-content"><div class="alert-title">' + title + '</div><div class="alert-message">' + message + '</div></div>';
            alertEl.className = 'alert ' + type + ' show';
            setTimeout(() => alertEl.classList.remove('show'), 5000);
        }

        // Handle form submission
        form.addEventListener('submit', async (e) => {
            e.preventDefault();
            submitBtn.classList.add('loading');
            submitBtn.querySelector('.btn-text').textContent = '发送中...';
            submitBtn.disabled = true;

            const data = {
                token: document.getElementById('token').value,
                openid: document.getElementById('openid').value,
                from: document.getElementById('from').value || undefined,
                desc: document.getElementById('desc').value,
                remark: document.getElementById('remark').value || undefined,
                url: document.getElementById('url').value || undefined
            };

            localStorage.setItem('flaremsg_token', data.token);
            localStorage.setItem('flaremsg_openid', data.openid);

            try {
                const response = await fetch('/send', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(data)
                });
                const result = await response.json();
                if (response.ok && result.errcode === 0) {
                    showAlert('消息发送成功！', '消息 ID: ' + result.msgid, 'success');
                    document.getElementById('desc').value = '';
                } else {
                    showAlert('发送失败', result.errmsg || '未知错误', 'error');
                }
            } catch (error) {
                showAlert('网络错误', error.message, 'error');
            } finally {
                submitBtn.classList.remove('loading');
                submitBtn.querySelector('.btn-text').textContent = '发送消息';
                submitBtn.disabled = false;
            }
        });
    </script>
</body>
</html>

`;
